### ISSUE TITLE
Reference index

### ISSUE THREAD

**Issue by misik** [TreesLab/NCLscan#10]
Hi,

I've a problem related to create_reference.py. 
NCLscan-1.6/bin/create_reference.py -c NCLscan-1.6/NCLscan.config
sh: NCLscan-1.6/bin/SeqOut: No such file or directory
cat: write error: Broken pipe
[bwa_index] Pack FASTA... 37.91 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=6907425852, availableWord=498031676
[BWTIncConstructFromPacked] 10 iterations done. 99999996 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 199999996 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 299999996 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 399999996 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 499999996 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 599999996 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 699999996 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 799999996 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 899999996 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 999999996 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 1099999996 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 1199999996 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 1299999996 characters processed.
....

NCLscan-1.6/bin/SeqOut cannot be found but the index can still be generated. The SeqOut file is actually named as SeqOut.cpp in the bin/ folder. Should I change the script as 

SeqOut_bin              = {NCLscan_bin}/SeqOut.cpp

or is there another way to correct this issue?

Thanks,
Meltem

**Comment by chenchiaying** [comment]
Hi,  

Before building the reference index, did you build the C++ code (step 2.4)? 
The cpp files (e.g. SeqOut.cpp) in bin folder have to do "make" to generate the executive files (e.g. SeqOut). 

best,
Chia-Ying
