### ISSUE TITLE
error : Format Error! Z3 is not available!

### ISSUE THREAD

**Issue by misik** [TreesLab/NCLscan#11]
Hello,

After running the NCLScan for 24 hr I got this error. What can be the reason? 

Thanks,
Meltem 

Read 63299 genes, 215674 transcripts and 1282859 exons from the gtf file.
# novoindex (2.7) - Universal k-mer index constructor.
# (C) 2008 - 2011 NovoCraft Technologies Sdn Bhd
# novoindex MP1/MP1.JS2.ndx MP1/MP1.JS2.fa 
# Creating 12 indexing threads.
# Building with 6-mer and step of 1 bp.
# novoindex construction dT = 0.1s
# Index memory size   0.000Gbyte.
# Done.
Problem processing command line arguments: Expecting integer value for score threshold. at '-t'
/opt/novocraft-2.07.18/novoalign -r A 1 -t 0,1 -d MP1/MP1.JS2.ndx -f MP1/MP1.main.unmapped_1.fastq MP1/MP1.main.unmapped_2.fastq --3Prime -o SAM 
Format Error! Z3 is not available!
Format Error! Z3 is not available!
Loaded 3227547748 letters in 524 sequences
Searched 0 bases in 0 sequences
Total time cost = 131.041696072 sec
Loaded 198051268 letters in 94359 sequences
Searched 0 bases in 0 sequences
Total time cost = 12.3649411201 sec
Loaded 28113910 letters in 27692 sequences
Searched 0 bases in 0 sequences
Total time cost = 2.79928803444 sec
Loaded 33138 letters in 1 sequences
Searched 0 bases in 0 sequences
Total time cost = 2.7208340168 sec
Format Error! Z3 is not available!
Format Error! Z3 is not available!
Traceback (most recent call last):
  File "NCLscan-1.6/bin/Add_read_count.py", line 118, in <module>
    add_read_count(args.result_tmp_file, args.result_sam_file, args.output, args.JSParser_bin)
  File "NCLscan-1.6/bin/Add_read_count.py", line 13, in add_read_count
    all_junc_read_with_ref = get_junc_read(result_sam_data, JSParser_bin)
  File "NCLscan-1.6/bin/Add_read_count.py", line 66, in get_junc_read
    junc_read_data = get_read_with_ref(junc_read_sam_data)
  File "NCLscan-1.6/bin/Add_read_count.py", line 46, in get_read_with_ref
    ref_id = re.sub("\.[0-9]*$", "", line[2])
IndexError: list index out of range
Traceback (most recent call last):
  File "NCLscan-1.6/bin/get_gene_name.py", line 91, in <module>
    add_gene_name(args.result_tmp_file, args.gene_anno, args.output)
  File "NCLscan-1.6/bin/get_gene_name.py", line 8, in add_gene_name
    result_tmp_data = read_TSV(result_tmp_file)
  File "NCLscan-1.6/bin/get_gene_name.py", line 64, in read_TSV
    with open(tsv_file) as data_reader:
IOError: [Errno 2] No such file or directory: 'MP1/MP1.result.tmp2'
Traceback (most recent call last):
  File "NCLscan-1.6/NCLscan.py", line 448, in <module>
    NCL_Scan4(config, datasets_list, args.project_name, args.output_dir)
  File "NCLscan-1.6/NCLscan.py", line 255, in NCL_Scan4
    final_tmp = read_TSV("{prefix}.result.tmp3".format(**config_options))
  File "NCLscan-1.6/NCLscan.py", line 279, in read_TSV
    with open(tsv_file) as data_reader:
IOError: [Errno 2] No such file or directory: 'MP1/MP1.result.tmp3'

**Comment by chiangtw** [comment]
NCLscan should be run with novoalign v3.
It seems that the option "-t a,b" had not been available in novoalign v2.
