### ISSUE TITLE
NCLscan error: "does not appear to be a valid novoindex. Code 9"

### ISSUE THREAD

**Issue by Swadha22** [TreesLab/NCLscan#15]
Hi,
I have been trying to use NCLscan Version 1.6 for one of my projects. I am getting this same error again and again:
"does not appear to be a valid novoindex. Code 9"
 I have the licence of NOVOCRAFT software for one month trial. Do you know why I am getting this type of error and what should I do to fix this?

I have attached the output file with this email.
[NCLscan_novoindex_error.txt](https://github.com/TreesLab/NCLscan/files/2395133/NCLscan_novoindex_error.txt)

Any help will be appreciated. Thanks in  advance,
Swadha

**Comment by chiangtw** [comment]
Hi,

This error message is probably due to the "empty" index file.
(You may check the file "[Project_name].JS2.fa" to see if it is empty.)

For further help, please provide the output of the following command: 
```
ls -lhtr /path/to/NCLscan_output_dir
```

Thanks for the report!

tw

**Comment by Swadha22** [comment]
Hey,
Thanks a lot for getting back!
Yes, it looks like that file is empty. Here is the list of output files below:

total 39G
-rw-r--r-- 1 roylab roylab 3.0G Sep 17 13:43 test_NCLscan.main.bwa.bam
-rw-r--r-- 1 roylab roylab 6.5G Sep 17 13:48 test_NCLscan.main.bwa.unmapped.sam
-rw-r--r-- 1 roylab roylab 232M Sep 17 13:50 test_NCLscan.main.bwa.unmapped.sam.id
-rw-r--r-- 1 roylab roylab 2.8G Sep 17 13:53 test_NCLscan.main.bwa.unmapped_1.fastq
-rw-r--r-- 1 roylab roylab 2.8G Sep 17 13:55 test_NCLscan.main.bwa.unmapped_2.fastq
-rw-r--r-- 1 roylab roylab 3.2G Sep 17 14:53 test_NCLscan.main.sam
-rw-r--r-- 1 roylab roylab 2.3G Sep 17 14:58 test_NCLscan.main.unmapped.sam
-rw-r--r-- 1 roylab roylab 179M Sep 17 14:58 test_NCLscan.main.unmapped.sam.id
-rw-r--r-- 1 roylab roylab 2.2G Sep 17 15:00 test_NCLscan.main.unmapped_1.fastq
-rw-r--r-- 1 roylab roylab 2.2G Sep 17 15:03 test_NCLscan.main.unmapped_2.fastq
-rw-r--r-- 1 roylab roylab 1.9G Sep 17 15:18 test_NCLscan.main.unmapped.fa
-rw-r--r-- 1 roylab roylab 1.9G Sep 17 15:19 test_NCLscan.unmapped.fa
-rw-r--r-- 1 roylab roylab 104M Sep 17 15:32 test_NCLscan.rG.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:32 test_NCLscan.un.psl
-rw-r--r-- 1 roylab roylab 104M Sep 17 15:32 test_NCLscan.rG.non_un.psl
-rw-r--r-- 1 roylab roylab 171K Sep 17 15:32 test_NCLscan.chi0.bed
-rw-r--r-- 1 roylab roylab 291K Sep 17 15:33 test_NCLscan.unmapped.2.fa
-rw-r--r-- 1 roylab roylab 307K Sep 17 15:33 test_NCLscan.coding.2.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:33 test_NCLscan.lncRNA.2.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:33 test_NCLscan.chrM.2.psl
-rw-r--r-- 1 roylab roylab  628 Sep 17 15:33 test_NCLscan.colinear.psl
-rw-r--r-- 1 roylab roylab 171K Sep 17 15:33 test_NCLscan.chi.bed
-rw-r--r-- 1 roylab roylab 9.2K Sep 17 15:33 test_NCLscan.preJS.bed
-rw-r--r-- 1 roylab roylab 8.8K Sep 17 15:33 test_NCLscan.preJS.info
-rw-r--r-- 1 roylab roylab 8.6K Sep 17 15:33 test_NCLscan.preJS.info2
-rw-r--r-- 1 roylab roylab 5.6K Sep 17 15:33 test_NCLscan.JS.info_1
-rw-r--r-- 1 roylab roylab 4.0K Sep 17 15:33 test_NCLscan.JS.info_2
-rw-r--r-- 1 roylab roylab 2.1K Sep 17 15:33 test_NCLscan.JS.info
-rw-r--r-- 1 roylab roylab 1.4K Sep 17 15:33 test_NCLscan.JS.cleaned.info
-rw-r--r-- 1 roylab roylab  32K Sep 17 15:33 test_NCLscan.preJS.seq
-rw-r--r-- 1 roylab roylab  32K Sep 17 15:33 test_NCLscan.preJS.seq2
-rw-r--r-- 1 roylab roylab  18K Sep 17 15:33 test_NCLscan.JS.seq_1
-rw-r--r-- 1 roylab roylab  15K Sep 17 15:33 test_NCLscan.JS.seq_2
-rw-r--r-- 1 roylab roylab 8.6K Sep 17 15:33 test_NCLscan.JS.seq12
-rw-r--r-- 1 roylab roylab 5.4K Sep 17 15:33 test_NCLscan.JS.seq
-rw-r--r-- 1 roylab roylab 5.4K Sep 17 15:33 test_NCLscan.JS.fa
-rw-r--r-- 1 roylab roylab 1.1M Sep 17 15:33 test_NCLscan.JS.ndx
-rw-r--r-- 1 roylab roylab 2.5G Sep 17 15:37 test_NCLscan.main_1.JS.sam
-rw-r--r-- 1 roylab roylab 2.5G Sep 17 15:40 test_NCLscan.main_2.JS.sam
-rw-r--r-- 1 roylab roylab 5.0G Sep 17 15:41 all.test_NCLscan.JS.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:41 all.test_NCLscan.JS.Parsered.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 tmp.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.JS.clear.fa
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.JS.GRCh37.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.linearJS
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.JS.GRCh37.2.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.tmp.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.tmp2.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.2.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:44 test_NCLscan.2.info.fa
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.2.info.GRCh37.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.2.chi.bed
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 temp.list
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.chi2.bed
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.chi3.bed
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.PreJS2.bed
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.PreJS2.info
-rw-r--r-- 1 roylab roylab    2 Sep 17 15:45 test_NCLscan.PreJS2.info2
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.info_1
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.info_2
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.cleaned.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.preIdx
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS1.preIdx
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS1.Idx
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.Idx
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.PreJS2.seq
-rw-r--r-- 1 roylab roylab    2 Sep 17 15:45 test_NCLscan.PreJS2.seq2
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.seq_1
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.seq_2
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.seq
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.prefa
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.fa
-rw-r--r-- 1 roylab roylab 1.1M Sep 17 15:45 test_NCLscan.JS2.ndx
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.main.JS2.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.1.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.1.result
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.ncl.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.JS2.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.result
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.JS2.result.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.result.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.2b.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.4.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.3.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.preResult
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.main_1.um3.fastq
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.main_2.um3.fastq
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.main.um3.fa
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.um3.fa
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.rG.um3.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.coding.um3.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.lncRNA.um3.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.chrM.um3.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.um3.colinear.psl
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.main.JS2b.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.1b.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.1b.result
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.JS2b.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.result.sam
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 all.test_NCLscan.b.result
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.3b.info
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.result.tmp
-rw-r--r-- 1 roylab roylab    0 Sep 17 15:45 test_NCLscan.4b.info

Thanks
Swadha

**Comment by chiangtw** [comment]
Hi,

It seems that most of the candidates of NCL events are not on the annotated exon boundaries.

You may check the following two NCL candidates files:
```
-rw-r--r-- 1 roylab roylab 171K Sep 17 15:33 test_NCLscan.chi.bed
-rw-r--r-- 1 roylab roylab 9.2K Sep 17 15:33 test_NCLscan.preJS.bed
```
The second(test_NCLscan.preJS.bed) is derived from the first(test_NCLscan.chi.bed) by correcting to the annotated exon boundaries.

Simply check the file size,  we see that it decreases from 171k to 9.2k.
And such decrease of NCL candidates then leads the pipeline to fails.

Thanks
tw
