### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by brianjohnhaas** [TreesLab/NCLscan#2]
Hi,

Is it possible to have access to the actual source code for NCLscan? It seems that just binaries  (in addition to a few wrapper scripts) are uploaded to github.

When trying to run the binary on my system, I see:
./NCL_Scan1: error while loading shared libraries: libstdc++.so.6: wrong ELF class: ELFCLASS64
./NCL_Scan2: error while loading shared libraries: libstdc++.so.6: wrong ELF class: ELFCLASS64
./NCL_Scan3: error while loading shared libraries: libstdc++.so.6: wrong ELF class: ELFCLASS64

**Comment by chiangtw** [comment]
Hi,

The updated version of NCLscan is under developing, with the new user interface and the source code.
It will be released recently as soon as possible.

Thanks for the report!

**Comment by brianjohnhaas** [comment]
In all honesty, the current version of the software shouldn't have been allowed to be published in its current form as largely closed source and also largely unusable.  

-Brian
(by iPhone)

**Comment by chiangtw** [comment]
Please see the latest version(v1.6) of NCLscan.
