### ISSUE TITLE
novoalign fails to create index

### ISSUE THREAD

**Issue by BarryDigby** [TreesLab/NCLscan#22]
Hi there, 

`create_reference.py` fails with the following error: 

```
Error: Invalid NA code in /data/bdigby/NCLscan/reference/AllRef.fa at line 51696593.
```
Inspecting the line in question: 
```
sed -n '51696593p' ../reference/AllRef.fa
>ENSP00000493376.2|ENST00000641515.2_2|ENSG00000186092.6_4|OTTHUMG00000001094.4_4|OTTHUMT00000003223.4_2|OR4F5-202|OR4F5|326|
```

This seems to be a novoalign problem, BWA creates the index without issue. 

- **NLCscan version**: v1.6
- **Novoalign**: novocraftV3.09.04. (occurs in v4 also)
- **Reference Genome files**:
-- gencode.v33lift37.annotation.gtf
-- gencode.v33lift37.lncRNA_transcripts.fa
-- gencode.v33lift37.pc_translations.fa
-- GRCh37.primary_assembly.genome.fa

Please find attached the error log. 

[nclscan.err.txt](https://github.com/TreesLab/NCLscan/files/4330623/nclscan.err.txt)

**Comment by colinhercus** [comment]
Hi Barry,

You need to look at the next line of the fasta as Novoindex line count is zero based.

Colin

**Comment by chiangtw** [comment]
Hi, Barry,

I think you might use the wrong file :sweat_smile:, 
 you should use  "gencode.v33lift37.pc_**transcripts**.fa.gz", 
not "gencode.v33lift37.pc_**translations**.fa".

tw

**Comment by chiangtw** [comment]
@colinhercus  Thanks for the information!

**Comment by colinhercus** [comment]
@BarryDigby 
At https://www.gencodegenes.org/human/release_33lift37.html

head -5  gencode.v33lift37.pc_translations.fa.gz
>ENSP00000493376.2|ENST00000641515.2_2|ENSG00000186092.6_4|OTTHUMG00000001094.4_4|OTTHUMT00000003223.4_2|OR4F5-202|OR4F5|326|
MKKVTAEAISWNESTSETNNSMVTEFIFLGLSDSQELQTFLFMLFFVFYGGIVFGNLLIV
ITVVSDSHLHSPMYFLLANLSLIDLSLSSVTAPKMITDFFSQRKVISFKGCLVQIFLLHF
FGGSEMVILIAMGFDRYIAICKPLHYTTIMCGNACVGIMAVTWGIGFLHSVSQLAFAVHL

You should be using
ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/GRCh37_mapping/gencode.v33lift37.pc_transcripts.fa.gz
