### ISSUE TITLE
why look for tools in the current working directory?

### ISSUE THREAD

**Issue by brianjohnhaas** [TreesLab/NCLscan#3]
Is it possible to have the software just look for tools either in the installation directory or via the PATH setting?

./NCLscan.sh simu_5X_100PE_1.fastq simu_5X_100PE_2.fastq 0 8 50
========== Start ===========
Mon Feb 29 13:23:48 EST 2016
============================
sh: ./bwa: No such file or directory
[samopen] no @SQ lines in the header.
[sam_read1] missing header? Abort!
Traceback (most recent call last):
  File "./NCL_Scan0.py", line 43, in <module>
    main()
  File "./NCL_Scan0.py", line 38, in main
    get_bwa_unmapped(args.Fastq_1, args.Fastq_2, args.Project_Name, args.bwa_index_prefix, args.bwa_thread)
  File "./NCL_Scan0.py", line 12, in get_bwa_unmapped
    os.mkdir("split_unmap.tmp")
OSError: [Errno 17] File exists: 'split_unmap.tmp'
cat: GRCh37.p13.genome.fa: No such file or directory
cat: GRCh37.p13.genome.fa: No such file or directory
cat: gencode.v19.pc_transcripts.fa: No such file or directory
cat: gencode.v19.lncRNA_transcripts.fa: No such file or directory
sh: ./novoindex: No such file or directory
sh: ./novoalign: No such file or directory
cat: 0.bwa.unmapped_1.fastq: No such file or directory
cat: 0.bwa.unmapped_2.fastq: No such file or directory
sh: ./blat: No such file or directory
cat: 0.rG.psl: No such file or directory
cat: 0.rG.psl: No such file or directory
PslChimeraFilter v0.4

sh: ./blat: No such file or directory
sh: ./blat: No such file or directory
sh: ./blat: No such file or directory
cat: 0.coding.2.psl: No such file or directory
cat: 0.lncRNA.2.psl: No such file or directory
cat: 0.chrM.2.psl: No such file or directory
JunctionSite2BED v0.3

Get annotation of exonic regions beginnig from exons colsed to a given position.

Example:
cat Pos.bed | ./JunctionSite2BED gencode.v18.annotation.gtf 500 300

Format Error!
Format Error!
sh: ./bedtools: No such file or directory
cat: 0.preJS.seq: No such file or directory
Format Error!
Format Error!
NCL_Scan3 v0.5
./NCL_Scan3	(null)
sh: ./novoindex: No such file or directory
sh: ./novoalign: No such file or directory
sh: ./novoalign: No such file or directory
sh: ./blat: No such file or directory
cat: 0.JS.GRCh37.psl: No such file or directory
sh: ./blat: No such file or directory
cat: 0.2.info.GRCh37.psl: No such file or directory
PslChimeraFilter v0.4

JunctionSite2BED v0.3

Get annotation of exonic regions beginnig from exons colsed to a given position.

Example:
cat Pos.bed | ./JunctionSite2BED gencode.v18.annotation.gtf 500 300

Format Error!
Format Error!
sh: ./bedtools: No such file or directory
cat: 0.PreJS2.seq: No such file or directory
Format Error!
Format Error!
sh: ./novoindex: No such file or directory
NCL_Scan4 v0.2.5
sh: ./novoalign: No such file or directory
rm: cannot remove '*.um3.psl': No such file or directory
sh: ./blat: No such file or directory
sh: ./blat: No such file or directory
sh: ./blat: No such file or directory
sh: ./blat: No such file or directory
cat: *.um3.psl: No such file or directory
Traceback (most recent call last):
  File "./Add_read_count.py", line 92, in <module>
    main()
  File "./Add_read_count.py", line 88, in main
    add_read_count(res_tmp_file, res_sam_file, output_file, args.JSParser_bin)
  File "./Add_read_count.py", line 13, in add_read_count
    all_junc_read_with_ref = get_junc_read(result_sam_data, JSParser_bin)
  File "./Add_read_count.py", line 66, in get_junc_read
    junc_read_data = get_read_with_ref(junc_read_sam_data)
  File "./Add_read_count.py", line 46, in get_read_with_ref
    ref_id = re.sub("\.[0-9]*$", "", line[2])
IndexError: list index out of range
Traceback (most recent call last):
  File "./get_gene_name.py", line 75, in <module>
    main()
  File "./get_gene_name.py", line 72, in main
    add_gene_name(res_tmp_file, anno_file, output_file)    
  File "./get_gene_name.py", line 8, in add_gene_name
    result_tmp_data = read_TSV(result_tmp_file)
  File "/seq/RNASEQ/TOOLS/NCLscan/NCLscan_v1.4/utils.py", line 8, in read_TSV
    with open(tsv_file) as data_reader:
IOError: [Errno 2] No such file or directory: '0.result.tmp2'
Traceback (most recent call last):
  File "./NCL_Scan5.py", line 30, in <module>
    NCL_Scan5(pj_name)
  File "./NCL_Scan5.py", line 11, in NCL_Scan5
    final_tmp = read_TSV("{PJ}.result.tmp3".format(PJ=pj_name))
  File "/seq/RNASEQ/TOOLS/NCLscan/NCLscan_v1.4/utils.py", line 8, in read_TSV
    with open(tsv_file) as data_reader:
IOError: [Errno 2] No such file or directory: '0.result.tmp3'
=========== Stop ============
Mon Feb 29 13:23:51 EST 2016
=============================

**Comment by chiangtw** [comment]
Please see the latest version(v1.6) of NCLscan.
