### ISSUE TITLE
How the last 2 parameters in configuration file: config.txt affect results and when the updated version will probably be released?

### ISSUE THREAD

**Issue by linatbeishan** [TreesLab/NCLscan#4]
Hi, I have 2 questions regarding to this software(v1.4).
1. After spending some efforts, I managed to run the test data, and the output is almost the same as the file provided(with 3 more colunms appended for each record), except the last record(listed below), which was missed in my result.
"chr1    67436642        +       chr1    67423742        +       MIER1   MIER1   1"
 But I have no idea about how the last 2 parameters in configuration file:config.txt will affect the output of my data(PE101 sequencing), particularly the "fragment size" parameter. Should I change these 2 parameters to "101 and 400" accordingly, or just leave it alone as the sequence length is shorter than 151, Could you kindly give some more suggestion?
2. I notice that you mentioned in another post that "the updated version wil be released recently as soon as possible". 
Will the updated version has a major difference regarding to the output result(e.g. detection algorithms changed, etc) or just polished with a nicer user interface. If it is the latter case, maybe I can continue with the v1.4, as I managed to get along with it now :-)

Thanks!

**Comment by chiangtw** [comment]
Hi, 
For the first part, perhaps you could provide me more information about your settings, such as the version of bwa, the quality score threshold, ... 

About the last 2 parameters in 'config.txt', you may just use the default "151 and 500", 
unless the length of your sequencing data is longer than 151, or the fragment size is longer than 500.
These 2 parameters decide the size of the pseudo-references, please make sure that they are big enough for your data.

The next update would only upgrade the user interface, the detection algorithm would not be changed.

Thanks!  :-)

**Comment by linatbeishan** [comment]
Thanks, tw.

Here are the softwares, data and script I used, hope this helps.
1. Softwares:
bwa: 0.7.12-r1039;
samtools: 0.1.19-44428cd
bedtools: bedtools-2.24.0
blat: (version:NA, last modified: 2016-02-16) http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/
novoalign: V3.04.01

2. Both reference and index are downloaded from the ftp:
ftp://treeslab1.genomics.sinica.edu.tw/NCLscan/

3. The script used:
./NCLscan.sh simu_5X_100PE_1.fastq simu_5X_100PE_2.fastq test_NCLscan 0 3 50 2>&1 | tee  test_NCLscan.log

linwei

**Comment by chiangtw** [comment]
Please try the latest version(v1.6) of NCLscan.
