### ISSUE TITLE
Is it possible to retrieve the pseudo-references??

### ISSUE THREAD

**Issue by Aufiero** [TreesLab/NCLscan#6]
Dear colleagues, I used NCLscan to detect circRNA molecules. 
From what I understood this tool uses pseudo-references as a strategy to detect this kind of molecules.
All pseudo reference are constructed where the exons are topologically inconsistent with the reference genome. A pseudo-reference is regarded as a circRNA candidate if it has at least one reads that maps to its NCLjuntion sites.
I had a look at the output files, but I didn't find any file containing the pseudo-references regarded as a circRNAs, maybe I missed it, so I was wondering is there such a file? 
Thanks,
S

**Comment by chiangtw** [comment]
Hi, 

Please check the file "[Project].JS2.fa", and you can use the candidate IDs(1st column of "[Project].result.tmp3") to get the needed sequences.

Note.
The pseudo-references used in NCLscan are just for the detection of the NCL junction sites.
