### ISSUE TITLE
JSFilter Segmentation fault

### ISSUE THREAD

**Issue by arthuryxt** [TreesLab/NCLscan#7]
Hi,

I am trying to run v1.6 and the first three steps ran smoothly, but I cannot make it through JSFilter. Could you please kindly check on that? Below are the prompt messages:

```
cat: write error: Broken pipe
sh: line 1: 55989 Done(1)                 cat .//run2_NCLscan_PE.main.JS2.sam
     55990 Segmentation fault      | /project/NCLscan_master/bin/JSFilter 10 10 .//all.run2_NCLscan_PE.1.result > .//all.run2_NCLscan_PE.1.sam
```

The input file "run2_NCLscan_PE.main.JS2.sam" exists and is valid though.

Thanks for your help.

**Comment by chiangtw** [comment]
Hi,

Please check the followings:
1. check the program "JSFilter" if it could be ran successfully. 
   (without any parameters, it should print out the help message.)
2. check the file size of "run2_NCLscan_PE.main.JS2.sam".
3. please provide the system information, such as the operating system, the memory size, ...

Thanks,

tw

**Comment by arthuryxt** [comment]
Dear tw,

Thanks a lot for your time and effort 👍 

1. JSFilter works find without parameters:
```
./JSFilter 

JSFilter [J. length] [A. length] [Result]

[J. length]        INTEGER     The valid length of cross-junction alignemnts.
[A. length]        INTEGER     The minimal length of alignemnts in both sides.
[Result]           STRING      The file name that reporting results.

Example: (for all)
cat all.A.sam | ./JSFilter 10 50 A.result > A.filtered.sam 

Example: (for single data set)
cat a1.sam | ./JSFilter 10 10 a1.result > a1.filtered.sam

```

2. the file "run2_NCLscan_PE.main.JS2.sam" is 372M, and below is the first a few lines:
```
@HD	VN:1.0	SO:unsorted
@PG	ID:novoalign	PN:novoalign	VN:V3.04.04	CL:novoalign -r A 1 -t 0,1 -d .//run2_NCLscan_PE.JS2.ndx -f .//run2_NCLscan_PE.main.unmapped_1.fastq .//run2_NCLscan_PE.main.unmapped_2.fastq --3Prime -o SAM
@SQ	SN:Truseq_LPE_NM_021080.3_2580_478_202_1.0	LN:1000	AS:run2_NCLscan_PE.JS2.ndx
...
Truseq_2__4_1_2_4	83	Truseq_2__4_1_2_2.24	441	0	100M	=	441	100	CTACAGCTACTACCTGTACTACATGTATGCCAACATCATGGTGCTCAACAACCTCCGCAGTTCCTCAGTTTGAAACTACATGTAATTACGTAGAAGCTAC	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	PG:Z:novoalign	AS:i:0	UQ:i:0	NM:i:0	MD:Z:100	PQ:i:4	SM:i:0	AM:i:0	ZS:Z:R	NH:i:16	HI:i:1	IH:i:1	Z3:i:540
```

3. system info.
```
cpu    48x AMD Opteron 6176 SE
ram    129.1 GB
arch   x86_64 / 64-bit
glib  2.19
Linux kernel 3.10.29
```

Thanks,
Arthur

**Comment by chiangtw** [comment]
Hi,

Do you have the novoalign license file? Is it in the same folder with novoalign?

Thanks,

tw

**Comment by arthuryxt** [comment]
Hi,

I do have a fresh two-month novoalign license file. It is in the same folder with novoalign. Without that, novoalign won't work with parameter "--3Prime".

Thanks,
Arthur

**Comment by chiangtw** [comment]
I guess this issue was due to the "array overflow" problem in JSFilter. (988c638826fcb9764664c89b88b8627c76de1e0c)
